### ISSUE TITLE
Interurban Trail through Ballinger Commons is no longer "very bumpy"

### ISSUE THREAD

**Issue by wildjo** [solarbirdy/NorthshoreBikeMap#1]
The trail has recently undergone construction and has been repaved.

**Comment by solarbirdy** [comment]
Really! Oh that's great news. Did Shoreline put out anything official about it?

**Comment by wildjo** [comment]
I do not know if Shoreline City Hall did, but here is an article from Shoreline Area News. The article mentions how Ballinger Commons is run by King County Housing Authority and that perhaps they are responsible for trail maintenance rather than City of Shoreline?

https://www.shorelineareanews.com/2024/07/interurban-trail-through-ballinger.html

**Comment by solarbirdy** [comment]
Oh, brilliant, thank you again! And I didn't know it was KCHA and them being responsible for the maintenance makes sense. (I'm subscribed to some City of Shoreline stuff but nothing KCHA because ... mostly why would I be? xD )

**Comment by solarbirdy** [comment]
Resolved, Version 1.4, dropped 29 August 2024. Thank you!

**Comment by solarbirdy** [comment]
[marked closed]
